Models/Wedding.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
namespace wedding_planner.Models
{
  public class Wedding
  {
    [Key]
    public int WeddingId { get; set; }

    [Required(ErrorMessage="Wedder One field is required.")]
    [MinLength(2)]
    [Display(Name = "Wedder One")]
    public string WedderOne { get; set; }

    [Required(ErrorMessage="Wedder Two field is required.")]
    [MinLength(2)]
    [Display(Name = "Wedder Two")]
    public string WedderTwo { get; set; }

    [Required(ErrorMessage="Wedding Date field is required.")]
    [DataType(DataType.Date)]
    [FutureDate]
    [Display(Name = "Date")]
    public DateTime WeddingDate { get; set; }

    [Required(ErrorMessage = "Address field is required.")]
    [Display(Name = "Wedding Address")]
    public string Address{ get; set; }

    public User Creater { get; set; }
    public List<UserWedding> RSVP { get; set; }
    public DateTime CreatedAt { get; set; } = DateTime.Now;
    public DateTime UpdatedAt { get; set; } = DateTime.Now;
  }
}

Models/WeddingsView.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace wedding_planner.Models
{
    public class WeddingsView
    {
    public List<Wedding> allWeddings;

  }
}

Controllers/UserController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using wedding_planner.Models;
namespace wedding_planner.Controllers
{
  public class UserController : Controller
  {
    private MyContext dbContext;
    // here we can "inject" our context service into the constructor
    public UserController(MyContext context)
    {
      dbContext = context;
    }
    [HttpGet("")]
    public IActionResult Index()
    {
      return View();
    }
    [HttpPost("user/register")]
    public IActionResult Register(UserRegistration newUser)
    {
      if (ModelState.IsValid)
      {
        if (dbContext.Users.Any(u => u.Email == newUser.Email))
        {
          ModelState.AddModelError("Email", "Email already in use!");
          return View("Index");
        }
        else
        {
          PasswordHasher<UserRegistration> Hasher = new PasswordHasher<UserRegistration>();
          newUser.Password = Hasher.HashPassword(newUser, newUser.Password);
          User NewUser = new User
          {
            FirstName = newUser.FirstName,
            LastName = newUser.LastName,
            Email = newUser.Email,
            Password = newUser.Password,
          };
          dbContext.Users.Add(NewUser);
          dbContext.SaveChanges();

          int uid = NewUser.UserId;
          HttpContext.Session.SetInt32("uid", uid);

          return RedirectToAction("Success", "Wedding");
        }
      }
      else
      {
        return View("Index");
      }
    }
    [HttpPost("user/login")]
    public IActionResult Login(UserLogin currentUser)
    {
      if (ModelState.IsValid)
      {
        User userInDb = dbContext.Users.FirstOrDefault(u => u.Email == currentUser.LoginEmail);
        if (userInDb == null)
        {
          // Add an error to ModelState and return to View!
          ModelState.AddModelError("LoginEmail", "Invalid Email/Password");
          return View("Index");
        }
        // Initialize hasher object
        var hasher = new PasswordHasher<UserLogin>();

        // verify provided password against hash stored in db
        var result = hasher.VerifyHashedPassword(currentUser, userInDb.Password, currentUser.LoginPassword);

        // result can be compared to 0 for failure
        if (result == 0)
        {
          // handle failure (this should be similar to how "existing email" is handled)
          ModelState.AddModelError("LoginPassword", "Invalid Email/Password");
          return View("Index");
        }
        int uid = userInDb.UserId;
        HttpContext.Session.SetInt32("uid", uid);

        return RedirectToAction("Success", "Wedding");
      }
      else
      {
        return View("Index");
      }
    }

    [HttpGet("user/logout")]
    public IActionResult Logout()
    {
      HttpContext.Session.Clear();
      return RedirectToAction("Index");
    }
  }
}

Controllers/WeddingController.cs
using Microsoft.EntityFrameworkCore;
using wedding_planner.Models;
using System.Linq;
using System.Collections.Generic;
using System;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Http;
namespace wedding_planner.Controllers
{
  public class WeddingController : Controller
  {
    private MyContext dbContext;
    // here we can "inject" our context service into the constructor
    public WeddingController(MyContext context)
    {
      dbContext = context;
    }
    [HttpGet("Dashboard")]
    public IActionResult Success()
    {
      if (HttpContext.Session.GetInt32("uid") == null)
      {
        return RedirectToAction("Index", "Home");
      }
      List<Wedding> AllWeddings = dbContext.Weddings
      .Include(w => w.RSVP)
      .ThenInclude(we => we.User)
      .Include(wedding => wedding.Creater)
      .ToList();

      List<int> WeddingsToDelete = new List<int>();
      DateTime CurrentTime = DateTime.Now;
      foreach (var wedding in AllWeddings)
      {
        if (wedding.WeddingDate < CurrentTime)
        {
          WeddingsToDelete.Add(wedding.WeddingId);
        }
      }
      if (WeddingsToDelete.Count > 0)
      {
        foreach (var wedding in WeddingsToDelete)
        {
          Wedding WeddingToDelete = dbContext.Weddings.FirstOrDefault(w => w.WeddingId == wedding);
          dbContext.Weddings.Remove(WeddingToDelete);
          dbContext.SaveChanges();
        }

      }
      int LoggedUser = (int)HttpContext.Session.GetInt32("uid");
      ViewBag.LoggedUser = LoggedUser;
      ViewBag.User = dbContext.Users.FirstOrDefault(u => u.UserId == (int)HttpContext.Session.GetInt32("uid"));

      int count = dbContext.Users
      .Include(u => u.Weddings)
      .ThenInclude(us => us.Wedding)
      .Where(use => use.Weddings.Any(user => user.UserId == LoggedUser))
      .Count();
      ViewBag.Count = count;
      return View(AllWeddings);
    }
    [HttpPost("Dashboard/new")]
    public IActionResult NewWedding(Wedding newWedding)
    {
      if (HttpContext.Session.GetInt32("uid") == null)
      {
        return RedirectToAction("Index", "Home");
      }
      if (ModelState.IsValid)
      {
        User LoggedUser = dbContext.Users.FirstOrDefault(u => u.UserId == (int)HttpContext.Session.GetInt32("uid"));
        newWedding.Creater = LoggedUser;
        dbContext.Weddings.Add(newWedding);
        LoggedUser.WeddingsCreated.Add(newWedding);
        dbContext.SaveChanges();

        ViewBag.LoggedUser = (int)HttpContext.Session.GetInt32("uid");
        int weddingid = newWedding.WeddingId;
        return RedirectToAction("OneWeddingView", new { weddingid = weddingid });
      }
      else
      {
        if (newWedding.WeddingDate.Year == 1)
        {
          if (ModelState.ContainsKey("WeddingDate") == true)
          {
            ModelState["WeddingDate"].Errors.Clear();
          }
          ModelState.AddModelError("WeddingDate", "Invalid Date");
        }
        return View("NewWeddingView");
      }
    }
    [HttpGet("wedding/new")]
    public IActionResult NewWeddingView()
    {
      if (HttpContext.Session.GetInt32("uid") == null)
      {
        return RedirectToAction("Index", "Home");
      }
      return View();
    }

    [HttpGet("wedding/{weddingid}")]
    public IActionResult OneWeddingView(int weddingid)
    {
      if (HttpContext.Session.GetInt32("uid") == null)
      {
        return RedirectToAction("Index", "Home");
      }
      Wedding OneWedding = dbContext.Weddings.FirstOrDefault(w => w.WeddingId == weddingid);

      List<User> RSVPUsers = dbContext.Users
      .Include(u => u.Weddings)
      .ThenInclude(u => u.Wedding)
      .Where(wed => wed.Weddings.Any(wedd => wedd.WeddingId == weddingid))
      .ToList();

      ViewBag.RSVPUsers = RSVPUsers;
      return View(OneWedding);
    }

    [HttpPost("wedding/delete/{weddingid}")]
    public IActionResult DeleteWedding(int weddingid)
    {
      if (HttpContext.Session.GetInt32("uid") == null)
      {
        return RedirectToAction("Index", "Home");
      }
      Wedding WeddingToDelete = dbContext.Weddings.FirstOrDefault(w => w.WeddingId == weddingid);
      dbContext.Weddings.Remove(WeddingToDelete);
      dbContext.SaveChanges();
      return RedirectToAction("Success");
    }

    [HttpPost("wedding/rsvp/{weddingid}")]
    public IActionResult RSVPWedding(int weddingid)
    {
      if (HttpContext.Session.GetInt32("uid") == null)
      {
        return RedirectToAction("Index", "Home");
      }
      Wedding WeddingToRSVP = dbContext.Weddings.FirstOrDefault(w => w.WeddingId == weddingid);
      int uid = (int)HttpContext.Session.GetInt32("uid");
      User LoggedUser = dbContext.Users.FirstOrDefault(u => u.UserId == uid);
      UserWedding newUserWedding = new UserWedding
      {
        WeddingId = weddingid,
        Wedding = WeddingToRSVP,
        UserId = uid,
        User = LoggedUser,
      };
      dbContext.UsersWeddings.Add(newUserWedding);
      dbContext.SaveChanges();
      return RedirectToAction("Success");
    }

    [HttpPost("wedding/unrsvp/{weddingid}")]
    public IActionResult UnRSVPWedding(int weddingid)
    {
      if (HttpContext.Session.GetInt32("uid") == null)
      {
        return RedirectToAction("Index", "Home");
      }
      Wedding WeddingToRSVP = dbContext.Weddings.FirstOrDefault(w => w.WeddingId == weddingid);
      int uid = (int)HttpContext.Session.GetInt32("uid");
      User LoggedUser = dbContext.Users.FirstOrDefault(u => u.UserId == uid);

      UserWedding UserWeddingToDelete = dbContext.UsersWeddings.FirstOrDefault(uw => uw.WeddingId == weddingid && uw.UserId == uid);
      dbContext.UsersWeddings.Remove(UserWeddingToDelete);
      dbContext.SaveChanges();
      return RedirectToAction("Success");
    }
  }
}

Views/Wedding/NewWeddingView.cshtml
@model Wedding
<div>
  <h1>Plan Your Wedding</h1>
  <a asp-action="Success" asp-controller="Wedding">Dashboard</a>
  <a asp-action="Logout" asp-controller="User">Logout</a>
</div>
<form asp-action="NewWedding"asp-controller="Wedding" method="post">
  <div class="form-group">
    <label asp-for="WedderOne"></label>
    <input asp-for="WedderOne" class="form-control">
    <span asp-validation-for="WedderOne" class="text-danger"></span>
  </div>
  <div class="form-group">
    <label asp-for="WedderTwo"></label>
    <input asp-for="WedderTwo" class="form-control">
    <span asp-validation-for="WedderTwo" class="text-danger"></span>
  </div>
  <div class="form-group">
    <label asp-for="WeddingDate"></label>
    <input asp-for="WeddingDate" class="form-control">
    <span asp-validation-for="WeddingDate" class="text-danger"></span>
  </div>
  <div class="form-group">
    <label asp-for="Address"></label>
    <input asp-for="Address" class="form-control">
    <span asp-validation-for="Address" class="text-danger"></span>
  </div>
  <button type="submit" class="btn btn-primary">Create</button>
</form>

Views/Wedding/OneWeddingView.cshtml
@model Wedding
<div>
  <h1>@Model.WedderOne and @Model.WedderTwo 's Wedding</h1>
  <a asp-action="Success" asp-controller="Wedding">Dashboard</a>
  <a asp-action="Logout" asp-controller="User">Logout</a>
</div>
<h5 class="text-center">Date: @Model.WeddingDate.ToString("MMMM dd, yyyy")</h5>
<h5 class="text-center">Address: @Model.Address</h5>
<h5 class="text-center">Guests:</h5>
<ul>
  @foreach (var user in ViewBag.RSVPUsers)
  {
    <li>@user.FirstName @user.LastName</li>
  }
</ul>

Views/Wedding/Success.cshtml
@model List<Wedding>
<div>
  <h1>Welcome @ViewBag.User.FirstName @ViewBag.User.LastName</h1>
  <h3>You RSVP to total of @ViewBag.Count weddings</h3>
  <a asp-action="Logout" asp-controller="User">Logout</a>
</div>
<table class="table table-striped table-hover">
<thead class="thead-dark">
    <tr>
      <th>Wedding</th>
      <th>Date</th>
      <th>Guest</th>
      <th>Action</th>
    </tr>
  </thead>
  <tbody>
    @foreach (var wedding in Model)
    {
      <tr>
        <td><a asp-action="OneWeddingView" asp-controller="Wedding" asp-route-weddingid="@wedding.WeddingId">@wedding.WedderOne & @wedding.WedderTwo</a></td>
        <td>@wedding.WeddingDate.ToString("MMMM dd, yyyy")</td>
        <td>@wedding.RSVP.Count</td>
        @if(wedding.Creater.UserId == ViewBag.LoggedUser)
        {
            <td>
              <form asp-action="DeleteWedding" asp-controller="Wedding" asp-route-weddingid="@wedding.WeddingId" method="post">
                <button class="btn btn-danger">Delete</button>
              </form></td>
        }
        else
        {
          if(wedding.RSVP.Exists(w => w.UserId == ViewBag.LoggedUser))
          {
            <td><form asp-action="UNRSVPWedding" asp-controller="Wedding" asp-route-weddingid="@wedding.WeddingId" method="post">
                <button class="btn btn-success">Un-RSVP</button>
                </form></td>
          }
          else
          {
            <td>
              <form asp-action="RSVPWedding" asp-controller="Wedding" asp-route-weddingid="@wedding.WeddingId" method="post">
                <button class="btn btn-success">RSVP</button>
              </form>
              </td>
          }
        }
      </tr>
    }
  </tbody>
</table>

<a asp-action="NewWeddingView" asp-controller="Wedding" class="btn btn-info">New Wedding</a>